services:
  - type: web
    name: flask-todo
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///test.db"
